version: '3.3'
services:

  mocker:
    image: dotronglong/faker:stable
    volumes:
      - "./mocks:/app/mocks"

  redis:
    image: redis
    hostname: redis

  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - database
      - redis
      - mocker
    ports:
      - "8080:8080"

  database:
    image: "postgres"
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist db data
    ports:
      - "5432:5432"

volumes:
  database-data:

